# Generated by Django 2.1 on 2019-01-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190102_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='info',
            name='type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '高级用户'), (1, '超级管理员')], default=0, verbose_name='用户类型'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
