# Generated by Django 2.1 on 2019-01-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='info',
            name='type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
