# Generated by Django 2.1 on 2019-01-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190102_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '高级用户'), (3, '普通管理员')], default=0, verbose_name='类别'),
        ),
    ]
