# Generated by Django 2.1 on 2019-01-02 05:32

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_id', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=50)),
                ('con', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('theme', models.IntegerField(choices=[(1, '简约'), (2, '清新'), (3, '雅致'), (4, '唯美')], default=1)),
                ('s', models.IntegerField(choices=[(1, '发布'), (2, '草稿')], default=2)),
                ('page_view', models.IntegerField(verbose_name='浏览量')),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='网站分类')),
                ('k', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.KeyWord', verbose_name='关键字')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guanzhu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tel', models.IntegerField(max_length=20)),
                ('eamil', models.EmailField(max_length=20)),
                ('word', models.CharField(max_length=20)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Usercategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='sc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self.Usercategory', verbose_name='个人分类'),
        ),
    ]
